name: Caller for Multilingual WF

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to deploy'
        required: false
        type: string
        default: 'latest'

jobs:
  caller-workflow:
    uses: missAnkita/Reusable-Workflows/.github/workflows/deploy-angular.yml@feature/test-multilingual
    with:
      #working-directory: .
      #function-app-name: ${{ github.event.inputs.function-app-name }}
      version: ${{ github.event.inputs.version }}
